import { FastifyBaseLogger } from "fastify";
import type { Server as SocketIOServer } from "socket.io";
import { addDIResolverName } from "@/lib/awilix/awilix.js";
import { withRepositories } from "@/lib/utils/repository.js";
import { ApplicationService } from "@/modules/application/application.service.js";
import { defaultChatMessageSelectorWithReadStatuses } from "@/database/team/repositories/chat-message/chat-message.repository.js";

export type AiMessagePersistenceService = {
    saveAiReply: (p: {
        teamId: string;
        chatId: string;
        userChatMemberId: string;
        initiatorUserId: string;
        content: string;
    }) => Promise<void>;
    saveAiError: (p: {
        teamId: string;
        chatId: string;
        userChatMemberId: string;
        initiatorUserId: string;
        content: string;
    }) => Promise<void>;
};

export const createService = (
    applicationService: ApplicationService,
    io: SocketIOServer,
    log: FastifyBaseLogger
): AiMessagePersistenceService => {
    const persistAndEmit = async ({
        teamId,
        chatId,
        userChatMemberId,
        initiatorUserId,
        content,
    }: {
        teamId: string;
        chatId: string;
        userChatMemberId: string;
        initiatorUserId: string;
        content: string;
    }) => {
        const chatMessageRepository =
            await applicationService.initChatMessageRepository(teamId);

        const message = await withRepositories(
            [chatMessageRepository],
            async (repo) =>
                repo.create({
                    data: {
                        chatId,
                        message: content,
                        autoGenerated: false,
                        isFromAiAgent: true,
                        visibleToMemberId: userChatMemberId,
                    },
                    select: defaultChatMessageSelectorWithReadStatuses,
                })
        );

        const payload = {
            ...message,
            chatMessageReadStatuses: {},
        };

        io.to(`user:${initiatorUserId}`).emit("chat:message:new", payload);
    };

    return {
        saveAiReply: async (params) => {
            try {
                await persistAndEmit(params);
            } catch (error) {
                log.error(
                    { error, chatId: params.chatId },
                    "Failed to persist AI reply"
                );
            }
        },

        saveAiError: async (params) => {
            try {
                await persistAndEmit(params);
            } catch (error) {
                log.error(
                    { error, chatId: params.chatId },
                    "Failed to persist AI error message"
                );
            }
        },
    };
};

addDIResolverName(createService, "aiMessagePersistenceService");
